import{a as m,S as u,i as n}from"./assets/vendor-B7yatFIi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();function d(i){const r="https://pixabay.com/api/",t="51376542-95e34f1d639dab3c27f4a47b0",a=new URLSearchParams({q:i,key:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:27});return m.get(`${r}?${a}`).then(e=>e.data.hits)}const l=document.querySelector(".gallery"),c=document.querySelector(".loader"),f=new u(".gallery a");function p(i){const r=i.map(t=>`<li><a class="img-link" href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" width="360" height="200"><ul class="img-meta">
      <li class="meta-list-item"><span class="meta-item-title">Likes</span> ${t.likes}</li>
      <li class="meta-list-item"><span class="meta-item-title">Views</span> ${t.views}</li>
      <li class="meta-list-item"><span class="meta-item-title">Comments</span> ${t.comments}</li>
      <li class="meta-list-item"><span class="meta-item-title">Downloads</span> ${t.downloads}</li>
      </ul>
      </a>
      </li>`).join("");l.innerHTML=r,f.refresh()}function g(){l.innerHTML=""}function h(){c.classList.remove("is-hidden")}function y(){c.classList.add("is-hidden")}const L=document.querySelector(".form");function b(i){i.preventDefault(),g();const r=i.target.elements["search-text"].value.trim();if(r)h(),d(r).then(t=>{if(t.length===0)return n.error({message:"Sorry there are no images matching your search query. Please try again!",position:"topRight"});p(t)}).catch(t=>n.error({message:t.message,position:"topRight"})).finally(()=>y()),i.target.reset();else return n.error({message:"Empty request. Try again!",position:"topRight"})}L.addEventListener("submit",b);
//# sourceMappingURL=index.js.map
